spring:
    application:
        name: busqueda-service
    profiles:
        active: dev

    mvc:
        format:
            date-time: iso

#Configuracion de Swagger

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /doc/swagger-ui.html

#Configuracion de Logs

logging:
  level:
    cl:
        duoc:
            busqueda: INFO
    org:
        hibernate:
            SQL: DEBUG

---

#Configuracion del perfil Dev 

spring:
    config:
        activate:
            on-profile: dev, prod

#Configuracion del JPA con hibernate

    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_necoarcmarket_busqueda}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${DB_USER:root}
        password: ${DB_PASS:}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            initialization-fail-timeout: 5000  # Si en 5 segundos Laragon no responde, el programa se apaga solo
            connection-timeout: 5000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

#Configuracion para que Flyway funcione

    flyway:
        enabled: true
        baseline-on-migrate: true

#ubicacion de puertos
server:
  port: ${PORT:8081}

services:
  envios:
    baseUrl: ${ENVIOS_SERVICE_URL:http://${DB_HOST:localhost}:8083}
  productos:
    baseUrl: ${PRODUCTOS_SERVICE_URL:http://${DB_HOST:localhost}:8081/v1/productos}
