spring.application.name=busqueda-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/db_neroarcmarket_busqueda?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

services.notificacion.url=http://localhost:8085/v1/notificaciones

#Formato de fechas otra vez
spring.mvc.format.date-time=iso
services.productos.url=http://localhost:8081/v1/productos
services.envios.url=http://localhost:8084/v1/envios