spring.application.name=carrito
# Puerto del microservicio
server.port=8087

# Configuración de Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_necoarcmarket_carrito?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root

# En Laragon por defecto la contraseña es vacía
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# URL para que otros lo encuentren
services.usuario.baseUrl=http://localhost:8080
service.producto.baseUrl=http://localhost:8081