spring:
  application:
    name: envio-service
  profiles:
    active: dev
  
# Configuración de Base de Datos
  datasource:
    url: jdbc:mysql://localhost:3306/db_necoarcmarket_envio?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:     # En Laragon por defecto la contraseña es vacía
    driver-class-name: com.mysql.cj.jdbc.Driver

# Configuración del JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true

# Puerto del microservicio
server:
  port: 8084

# URL para que otros lo encuentren
services:
  ordenes:
    baseUrl: http://localhost:8088

# Configuración para que funcione swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: dev, prod

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_necoarcmarket_envio}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:}

server:
  port: ${PORT:8084}

services:
  ordenes:
    baseUrl: ${ORDENES_SERVICE_URL:http://${DB_HOST:localhost}:8088}