spring:
    application:
      name: carrito-service

#Configuramos y activamos el perfil de dev para que se levante el DataLoader
    profiles:
        active: dev

    mvc:
        format:
            date-time: iso
# Puerto del microservicio
server:
  port: ${PORT:8087}

#Configuracion de Swagger

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /doc/swagger-ui.html

#Configuracion de Logs

logging:
  level:
    cl:
        duoc:
            carrito: INFO
    org:
        hibernate:
            SQL: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev, prod

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_necoarcmarket_carrito}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:}

server:
  port: ${PORT:8087}

service:
  usuario:
    baseUrl: ${USUARIO_SERVICE_URL:http://${DB_HOST:localhost}:8080}
  producto:
    baseUrl: ${PRODUCTO_SERVICE_URL:http://${DB_HOST:localhost}:8081}

  jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

#Configuracion para que Flyway funcione

  flyway:
      enabled: true
      baseline-on-migrate: true