CREATE TABLE carrito(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_Usuario BIGINT NOT NULL,
    id_Producto BIGINT NOT NULL,
    cantidad INT NOT NULL DEFAULT 0,
    monto_Total INT NOT NULL DEFAULT 0
);