spring:
  application:
    name: producto-service
  profiles:
    active: dev # Si lo corres en Laragon/IDE, usará dev por defecto

# Configuracion de Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# Configuracion de Logs
logging:
  level:
    cl:
      duoc:
        productos: INFO
    org:
      hibernate:
        SQL: DEBUG

---

# 📍 El truco infalible: Esta sección ahora se activará tanto en DEV como en PROD
spring:
  config:
    activate:
      on-profile: dev, prod 

  # Configuracion del JPA con hibernate e inyección dinámica
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_necoarcmarket_productos}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 5000  
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuracion para que Flyway funcione
  flyway:
    enabled: true
    baseline-on-migrate: true

# Ubicacion de puertos
server:
  port: ${PORT:8081}

# Servicios Externos
services:
  inventario:
    baseUrl: ${INVENTARIO_SERVICE_URL:http://${DB_HOST:localhost}:8082/v1/inventario}